### ISSUE TITLE
Support for Google Cloud Storage

### ISSUE THREAD

**Issue by 0xCAP** [jeffminsungkim/nestjs-multer-extended#103]
Is support for GCS in the works? Otherwise I'd be glad to contribute to this repo by working on it.

**Comment by jeffminsungkim** [comment]
Hi, @0xCAP.
Thanks for opening an issue. Haven't supported GCS yet.
Sounds good to me. Would you like to create a PR? 😄

**Comment by 0xCAP** [comment]
Ok, that's fine. I started looking into the code, and found out that it's pretty heavily bound to S3. Since providing support for GCS file upload would introduce pretty big (and possibly breaking) changes to the module, I think we could benefit from planning how to proceed ahead of the implementation.

**Comment by jeffminsungkim** [comment]
Good point. I completely understand your concern. Probably, we should implement a module that could handle GCS configs and an interceptor for an upload. That's all I can think of now.
