### ISSUE TITLE
Asynchronous configuration don't work

### ISSUE THREAD

**Issue by ES-SOFYANY** [jeffminsungkim/nestjs-multer-extended#163]
when i import module like:

`
imports: [
        MulterExtendedModule.registerAsync({
            useFactory: (config: ConfigService) => config.get('s3'),
            inject: [Config]
        })
    ]
`
this error is displayed:

Error: **Nest can't resolve dependencies of the MULTER_EXTENDED_S3_OPTIONS (?). Please make sure that the argument ConfigService at index [0] is available in the MulterExtendedModule context.**

**Comment by gimyboya** [comment]
@ES-SOFYANY This issue has been solved in #157 you probably need to update to latest version

**Comment by jeffminsungkim** [comment]
@ES-SOFYANY
Like gimyboya said above, you should download the latest version. Thank you.
