### ISSUE TITLE
Make access keys optional?

### ISSUE THREAD

**Issue by ghempton** [jeffminsungkim/nestjs-multer-extended#170]
Would like to leverage IAM roles in production: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-iam.html

In development, it might also make sense to not use explicit keys and instead use the local configuration in `~/.aws`.

**Comment by jeffminsungkim** [comment]
Yeah, that's a good idea! 😃 Would you like to create a PR for this?
