### ISSUE TITLE
Upload files other than image

### ISSUE THREAD

**Issue by sandeshgb** [jeffminsungkim/nestjs-multer-extended#195]
I want to upload pdf and doc files. If I try to upload a pdf file it gives bad request error with message "Invalid Image File Type".

I have gone through the docs, but couldn't find enough of how to achieve it. It would be very helpful if you could provide me with a code-snippet / example for same.

Thanks!!

**Comment by jeffminsungkim** [comment]
@sandeshgb 
You should undefined `fileFilter` property. This is because, the default behavior of this module is to upload an image.
```typescript
@Post('upload')
@UseInterceptors(AmazonS3FileInterceptor('file', { fileFilter: undefined }))
async uploadNonImageFileWithoutFilter(@UploadedFile() file: any): Promise<any> {
  return file;
}
```

Thank you.
