### ISSUE TITLE
Requesting support for GCloud Storage

### ISSUE THREAD

**Issue by ianjaspersantos** [jeffminsungkim/nestjs-multer-extended#238]
I see this package with multi functionality, functions like auto naming, resizing, path configuration. Hope to see this package support Gcloud storage too cause right now community package for it is lacking this functionality. Thanks

**Comment by jeffminsungkim** [comment]
Thanks for opening an issue @ianjaspersantos 
We've already talked about this issue #103 earlier. Possibly support the Google cloud storage in the future.
