### ISSUE TITLE
Allow specific image types

### ISSUE THREAD

**Issue by sandeshgb** [jeffminsungkim/nestjs-multer-extended#243]
I need to know what values can "fileFilter" accept for images other than jpeg and png.
For example if I want to upload an image with extension .jpg or just want to allow only .png extension how to implement these scenarios.

**Comment by jeffminsungkim** [comment]
Thanks for opening an issue @sandeshgb 

If I understand your question correctly, you should make your own file filter and use them 

For example,

```typescript
filterJpgAndPngOnly(req, file, cb) {
    const { mimetype } = file;
    const extension = mimetype.substring(mimetype.lastIndexOf('/') + 1);

    // check extension is JPG or PNG

    // if not throw an error

    return cb(null, true);
  }

@Post('upload')
@UseInterceptors(AmazonS3FileInterceptor('file', { fileFilter: filterJpgAndPngOnly }))
async uploadImage(@UploadedFile() file: any): Promise<any> {
  return file;
}
```
