### ISSUE TITLE
Extract Dominant Color On Image Feature

### ISSUE THREAD

**Issue by ianjaspersantos** [jeffminsungkim/nestjs-multer-extended#254]
I'd like to also open this feature request in conjunction to https://github.com/jeffminsungkim/nestjs-multer-extended/issues/253 which extracting the hash of the image but in this case the dominant color of the image as a placeholder while loading in the image.. Example of this is https://unsplash.com/ and https://ar.pinterest.com/ which uses this kind of scenario. Thanks 🥇

**Comment by jeffminsungkim** [comment]
Could you give us more examples?

**Comment by ianjaspersantos** [comment]
<img width="1440" alt="Screen Shot 2020-10-17 at 2 10 00 PM" src="https://user-images.githubusercontent.com/57083058/96329781-9bc36980-1082-11eb-853a-59c80cd64b05.png">
<img width="1440" alt="Screen Shot 2020-10-17 at 2 10 02 PM" src="https://user-images.githubusercontent.com/57083058/96329788-a8e05880-1082-11eb-9d42-5317a48740af.png">
<img width="1440" alt="Screen Shot 2020-10-17 at 2 10 04 PM" src="https://user-images.githubusercontent.com/57083058/96329789-aaaa1c00-1082-11eb-96fe-9c0fea165840.png">
<img width="1440" alt="Screen Shot 2020-10-17 at 2 10 05 PM" src="https://user-images.githubusercontent.com/57083058/96329791-abdb4900-1082-11eb-966d-50d900448087.png">

Here are some samples. Where instead of blurhash placeholder, it will show the dominant color of an image as a loading indicator. Definitely extracting the hex color of the image.

**Comment by ianjaspersantos** [comment]
It still need some discussion
