### ISSUE TITLE
Issues on M1 Mac

### ISSUE THREAD

**Issue by MarcGirouxLeeroy** [jeffminsungkim/nestjs-multer-extended#438]
Since the lib is using Sharp, for M1 Mac compatibility you need to bump the version to 0.28.0 at least (0.28.3 at the time of this post). Otherwise the install process crashes.

```npm info run sharp@0.26.3 install node_modules/nestjs-multer-extended/node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)```

from discussion here
[https://github.com/lovell/sharp/issues/2781](https://github.com/lovell/sharp/issues/2781)

**Comment by JustDoItSascha** [comment]
Is this fixed?
