### ISSUE TITLE
Random filenames

### ISSUE THREAD

**Issue by volbrene** [jeffminsungkim/nestjs-multer-extended#61]
Hello,
is it possible to add random filenames before uploading to s3?

Thanks

- volbrene

**Comment by jeffminsungkim** [comment]
Hi @volbrene Thanks for opening an issue.
Your inquiry is currently unavailable. Could you please provide an example of what you are trying to achieve?

**Comment by volbrene** [comment]
Hello @jeffminsungkim, currently a file name must not be the same, otherwise the file is overwritten in s3. I would like to prevent that.

**Comment by jeffminsungkim** [comment]
Good point! Would you like to create a PR for this?

**Comment by volbrene** [comment]
I have add a Idea for my problem. Please review
